[package]
name = "zk-jam"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
eyre = "0.6"
serde_json.workspace = true
zk-jam-benchmark = { path = "../benchmark" }
zk-jam-openvm-backend = { path = "../openvm-backend" }
zk-jam-refine-interface = { path = "../refine-interface" }
