import { Info } from "lucide-react";
import { motion } from "motion/react";
import { Badge, Card } from "./ui";
import type { Language } from "../i18n";
import { copy } from "../i18n";
import type { SimulationResult } from "../model/types";
import { formatGas } from "../model/formulas";

const seconds = (value: number | null) => value == null ? "—" : value < 1 ? `${Math.round(value * 1000)} ms` : `${value.toFixed(value < 10 ? 2 : 1)} s`;
export function Metrics({ language, result }: { language: Language; result: SimulationResult }) {
  const t = copy[language]; const m = result.metrics;
  const item = (label: string, value: string, source: string) => <div className="metric-row"><span>{label}<Info size={11} /></span><strong>{value}</strong><Badge>{source}</Badge></div>;
  return <Card className="metrics-card"><div className="card-heading"><div><div className="eyebrow">{t.metrics}</div><div className="card-subheading">{result.runtime.provers.length} provers · {result.runtime.producer.name} producer</div></div><span className="live-dot">LIVE</span></div>{item(t.gas, formatGas(m.gasEquivalent), "DERIVED")}{item(t.proof, seconds(m.proofAvg), "OPENVM + DERIVED")}{item(t.reportMetric, seconds(m.workReport), "DERIVED")}{item(t.da, seconds(m.workDaTwoThird), "JAM MODEL")}{item(t.blockMetric, seconds(m.blockTwoThird), "DERIVED")}{item(t.logicalP50, seconds(m.logicalReadyP50), "DERIVED")}{item(t.logicalP90, seconds(m.logicalReadyP90), "DERIVED")}{item(t.logicalP99, seconds(m.logicalReadyP99), "DERIVED")}{item(t.groupReady, seconds(m.groupReadyP50), "DERIVED")}{item(t.ordinaryReady, seconds(m.ordinaryReadyP50), "DERIVED")}{item(t.daNode, `${m.daStoredPerNodeMb.toFixed(2)} MB`, "DERIVED")}{item(t.packagesNode, `${m.workPackagesPerNode.toFixed(2)}`, "DERIVED")}{item(t.externalFetch, seconds(m.groupExternalFetchSeconds), "DERIVED")}{item(t.replication, seconds(m.groupInternalReplicationSeconds), "DERIVED")}{item(t.coordination, seconds(m.groupCoordinationSeconds), "DERIVED")}{item(t.groupVerify, seconds(m.groupVerifySeconds), "DERIVED")}{item(t.sourceUtil, `${(m.sourceUtilization * 100).toFixed(0)}%`, "DERIVED")}{item(t.backboneUtil, `${(m.backboneUtilization * 100).toFixed(0)}%`, "DERIVED")}{item(t.homeWanUtil, `${(m.homeWanUtilization * 100).toFixed(0)}%`, "DERIVED")}{item(t.verifyUtil, `${(m.verifyUtilization * 100).toFixed(0)}%`, "DERIVED")}{item(t.smallDa, `${m.smallNodeDaMbps.toFixed(1)} Mbps`, "DERIVED")}{item(t.clusters, `~${Math.ceil(m.requiredClusters).toLocaleString()}`, "DERIVED")}{m.gasEquivalent > 5e9 && <Badge className="stress-badge">{t.above}</Badge>}<div className="metrics-foot"><span>Group slots <b>{m.groupedSlots.toLocaleString()}</b></span><span>Ordinary <b>{m.ordinarySlots.toLocaleString()}</b></span><span>Load <b>{Math.round(result.params.networkLoad * 100)}%</b></span></div><motion.div className="pressure" animate={{ opacity: [0.65, 1, 0.65] }} transition={{ duration: 2.8, repeat: Infinity }}><span>{t.groupBottleneck}</span><strong className="ok">{m.groupCriticalPath}</strong></motion.div><div className="pressure"><span>{t.dominant}</span><strong className="ok">{m.dominantBottleneck}</strong></div></Card>;
}
