export type Language = "en" | "zh" | "ja" | "fr";

const english = {
  subtitle: "Block validation and Work proving on separate timelines",
  parameters: "Parameters", params: "Parameters", core: "Core controls", groupShare: "Group share", nodes: "Nodes / group", workload: "ETH Blocks / Work Item", load: "Network load", smallReference: "Home-node reference", apply: "Apply parameters", reroll: "Reroll topology", pending: "Pending", physical: "Physical validator nodes", interval: "Block → 2/3 Ready",
  metrics: "Model metrics", work: "Work pipeline", block: "Block pipeline", refine: "REFINE", prove: "PROVE + DA", aggregate: "AGGREGATE", report: "REPORT READY", gate: "WORK COMPLETE", published: "BLOCK PUBLISHED", propagate: "PROPAGATE", verify: "VERIFY", consensus: "CONSENSUS", ready: "66.7% READY", waiting: "WAITING", receiving: "RECEIVING", verifying: "VERIFYING", legend: "LIVE SIMULATION", above: "ABOVE GRAY CENTER CORE ENVELOPE",
  gas: "JAM gas equivalent", proof: "Proof / item", reportMetric: "Work → Report", da: "Work DA → 2/3", blockMetric: "Block → 2/3 Ready", logicalP50: "Logical Ready P50", logicalP90: "Logical Ready P90", logicalP99: "Logical Ready P99", groupReady: "Group Ready P50", ordinaryReady: "Ordinary Ready P50", daNode: "DA / Group Node", packagesNode: "Work Packages / Group Node", externalFetch: "Group external fetch", replication: "Internal replication", coordination: "Internal coordination", groupVerify: "Group verify", groupBottleneck: "Group bottleneck", smallDa: "Home-node DA / node", clusters: "Required prover clusters", sourceUtil: "Source utilization", backboneUtil: "Backbone utilization", homeWanUtil: "Home WAN utilization", verifyUtil: "Verify utilization", dominant: "Dominant bottleneck", play: "PAUSE", resume: "PLAY", slot: "SLOT", producer: "PRODUCER", prover: "PROVER", source: "SOURCE",
  loadHint: "Controls active cores and arrival pressure; it does not change single-item proof latency.", groupHint: "One Group remains one logical consensus weight.", nodesHint: "More nodes increase fetch / verify parallelism, but shard caps, home-WAN capacity and coordination create diminishing returns.", workloadHint: "1 ETH block ≈ 33.3M JAM gas; 150 ETH blocks = 5B Gray-center gas.", mapNote: "Representative nodes shown; quorum is always 1,023 logical weights.",
} as const;

export const copy = {
  en: english,
  zh: { ...english, subtitle: "区块验证与 Work proving 分离建模", parameters: "参数", params: "参数", core: "核心参数", groupShare: "Group 比例", nodes: "每组节点数", load: "网络荷载", smallReference: "家庭节点参考", apply: "应用参数", reroll: "重随机拓扑", pending: "待应用", physical: "物理验证节点", interval: "Block → 2/3 Ready", metrics: "模型指标", work: "Work 流水线", block: "Block 流水线", reportMetric: "Work → Report", da: "Work DA → 2/3", blockMetric: "Block → 2/3 Ready", logicalP50: "Logical Ready P50", logicalP90: "Logical Ready P90", logicalP99: "Logical Ready P99", groupReady: "Group Ready P50", ordinaryReady: "普通 Ready P50", daNode: "DA / Group Node", packagesNode: "Work Packages / Group Node", externalFetch: "Group 外部获取", replication: "内部复制", coordination: "内部协调", groupVerify: "Group 验证", groupBottleneck: "Group 瓶颈", smallDa: "家庭节点 DA / node", clusters: "所需 prover clusters", sourceUtil: "源出口利用率", backboneUtil: "骨干网利用率", homeWanUtil: "家庭 WAN 利用率", verifyUtil: "验证利用率", dominant: "主要瓶颈", loadHint: "决定 active cores 与到达压力，不改变单个 Work Item proof latency。", groupHint: "一个 Group 始终只有一个逻辑共识权重。", nodesHint: "更多节点增加获取与验证并行度，但 shard 上限、家庭 WAN 和协调开销会形成收益递减。", mapNote: "地图仅显示代表性节点；quorum 始终按 1,023 个逻辑权重计算。" },
  ja: { ...english, subtitle: "ブロック検証と Work proving を別タイムラインで表示", parameters: "パラメータ", params: "パラメータ", core: "主要パラメータ", groupShare: "Group 比率", nodes: "Group 内ノード数", load: "ネットワーク負荷", smallReference: "家庭ノード基準", apply: "適用", reroll: "トポロジ再抽選", pending: "未適用", physical: "物理バリデータノード", interval: "Block → 2/3 Ready", logicalP50: "Logical Ready P50", logicalP90: "Logical Ready P90", logicalP99: "Logical Ready P99", groupReady: "Group Ready P50", ordinaryReady: "通常 Ready P50", daNode: "DA / Group Node", packagesNode: "Work Packages / Group Node", externalFetch: "Group 外部取得", replication: "内部複製", coordination: "内部調整", groupVerify: "Group 検証", groupBottleneck: "Group ボトルネック", smallDa: "家庭ノード DA / node", sourceUtil: "ソース利用率", backboneUtil: "バックボーン利用率", homeWanUtil: "家庭 WAN 利用率", verifyUtil: "検証利用率", dominant: "主要ボトルネック", loadHint: "Active cores と到着圧力を変えますが、単一 item の proof latency は変えません。", groupHint: "1 Group は常に1つの論理コンセンサス重みです。", nodesHint: "ノード数を増やすと並列度は上がりますが、shard 上限・家庭 WAN・調整コストで収穫逓減します。", mapNote: "代表ノードのみ表示。quorum は常に1,023論理重みです。" },
  fr: { ...english, subtitle: "Validation de bloc et proving Work sur deux chronologies", parameters: "Paramètres", params: "Paramètres", core: "Contrôles principaux", groupShare: "Part Group", nodes: "Nœuds / groupe", load: "Charge réseau", smallReference: "Référence nœud résidentiel", apply: "Appliquer", reroll: "Régénérer la topologie", pending: "À appliquer", physical: "Nœuds validateurs physiques", interval: "Block → 2/3 Ready", logicalP50: "Ready logique P50", logicalP90: "Ready logique P90", logicalP99: "Ready logique P99", groupReady: "Ready Group P50", ordinaryReady: "Ready ordinaire P50", daNode: "DA / nœud Group", packagesNode: "Work Packages / nœud Group", externalFetch: "Fetch externe Group", replication: "Réplication interne", coordination: "Coordination interne", groupVerify: "Vérification Group", groupBottleneck: "Goulot Group", smallDa: "DA / nœud résidentiel", sourceUtil: "Utilisation source", backboneUtil: "Utilisation backbone", homeWanUtil: "Utilisation WAN résidentiel", verifyUtil: "Utilisation vérification", dominant: "Goulot principal", loadHint: "Contrôle les cores actifs et la pression d’arrivée, sans changer la latence d’un item.", groupHint: "Un Group reste un seul poids logique de consensus.", nodesHint: "Plus de nœuds augmente le parallélisme, mais les limites de shard, du WAN résidentiel et de coordination créent des rendements décroissants.", mapNote: "Nœuds représentatifs uniquement; quorum toujours calculé sur 1 023 poids logiques." },
} as const;
